{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.operator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slurm-operator.name" . }}
  namespace: {{ include "slurm-operator.namespace" . }}
  labels:
    {{- include "slurm-operator.operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      {{- include "slurm-operator.operator.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "slurm-operator.operator.labels" . | nindent 8 }}
    spec:
      hostname: {{ include "slurm-operator.name" . }}
      priorityClassName: {{ default "" .Values.priorityClassName }}
      serviceAccountName: {{ include "slurm-operator.operator.serviceAccountName" . }}
      {{- include "slurm-operator.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: slurm-operator
          image: {{ include "slurm-operator.imageRef" . }}
          imagePullPolicy: {{ include "slurm-operator.imagePullPolicy" . }}
          args:
            - --cluster-workers
            - {{ default 1 .Values.operator.clusterWorkers | quote }}
            - --nodeset-workers
            - {{ default 1 .Values.operator.nodesetWorkers | quote }}
            - --zap-log-level
            - {{ default "info" .Values.operator.logLevel | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
{{- end }}{{- /* if .Values.operator.enabled */}}
