{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if and .Values.mariadb.enabled .Values.accounting.external.enabled -}}
  {{- fail "Mutually Exclusive: accounting.external.enabled=true; mariadb.enabled=true" -}}
{{- end }}{{- /* if and .Values.mariadb.enabled .Values.accounting.external.enabled */}}

{{- if and .Values.accounting.enabled (not .Values.accounting.external.enabled) .Values.mariadb.auth.existingSecret -}}
  {{- $secretName := (include "mariadb.secretName" .) -}}
  {{- $mariadbPassword := (randAlphaNum 32 | b64enc) -}}
  {{- $mariadbReplicationPassword := (randAlphaNum 32 | b64enc) -}}
  {{- $mariadbRootPassword := (randAlphaNum 32 | b64enc) -}}
  {{- if (lookup "v1" "Secret" (include "slurm.namespace" .) $secretName) -}}
    {{- $mariadbPassword = get (lookup "v1" "Secret" (include "slurm.namespace" .) $secretName).data "mariadb-password" -}}
    {{- $mariadbReplicationPassword = get (lookup "v1" "Secret" (include "slurm.namespace" .) $secretName).data "mariadb-replication-password" -}}
    {{- $mariadbRootPassword = get (lookup "v1" "Secret" (include "slurm.namespace" .) $secretName).data "mariadb-root-password" -}}
  {{- end }}{{- /* if (lookup "v1" "Secret" (include "slurm.namespace" .) $secretName) */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "slurm.namespace" . }}
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-password: {{ $mariadbPassword }}
  mariadb-replication-password: {{ $mariadbReplicationPassword }}
  mariadb-root-password: {{ $mariadbRootPassword }}
{{- end }}{{- /* if and .Values.accounting.enabled (not .Values.accounting.external.enabled) .Values.mariadb.auth.existingSecret */}}
