{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if and .Values.webhook.enabled .Values.certManager.enabled }}
---
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "slurm-operator.certManager.selfIssuer" . }}
  namespace: {{ include "slurm-operator.namespace" . }}
  labels:
    {{- include "slurm-operator.webhook.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "slurm-operator.certManager.rootCA" . }}
  namespace: {{ include "slurm-operator.namespace" . }}
  labels:
    {{- include "slurm-operator.webhook.labels" . | nindent 4 }}
spec:
  commonName: {{ include "slurm-operator.certManager.rootCA" . }}
  secretName: {{ include "slurm-operator.certManager.rootCA" . }}
  isCA: true
  duration: {{ .Values.certManager.duration | default "43800h0m0s" | quote }}
  renewBefore: {{ .Values.certManager.renewBefore | default "8760h0m0s" | quote }}
  issuerRef:
    name: {{ include "slurm-operator.certManager.selfIssuer" . }}
---
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "slurm-operator.certManager.rootIssuer" . }}
  namespace: {{ include "slurm-operator.namespace" . }}
  labels:
    {{- include "slurm-operator.webhook.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "slurm-operator.certManager.rootCA" . }}
---
# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certManager.secretName }}
  namespace: {{ include "slurm-operator.namespace" . }}
  labels:
    {{- include "slurm-operator.webhook.labels" . | nindent 4 }}
spec:
  commonName: {{ include "slurm-operator.certManager.selfCert" . }}
  secretName: {{ .Values.certManager.secretName }}
  duration: {{ .Values.certManager.duration | default "43800h0m0s" | quote }}
  renewBefore: {{ .Values.certManager.renewBefore | default "8760h0m0s" | quote }}
  issuerRef:
    name: {{ include "slurm-operator.certManager.rootIssuer" . }}
  dnsNames:
    - {{ include "slurm-operator.webhook.name" . }}
    - {{ include "slurm-operator.webhook.name" . }}.{{ include "slurm-operator.namespace" . }}.svc
{{- end }}{{- /* if and .Values.webhook.enabled .Values.certManager.enabled */}}
