{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "slurm.compute.name" . }}
  namespace: {{ include "slurm.namespace" . }}
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "slurm.compute.selectorLabels" . | nindent 4 }}
  ports:
    - name: slurmd
      protocol: TCP
      port: {{ include "slurm.compute.port" . }}
      targetPort: {{ include "slurm.compute.port" . }}
