{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.accounting.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "slurm.accounting.name" . }}
  namespace: {{ include "slurm.namespace" . }}
  labels:
    {{- include "slurm.accounting.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "slurm.accounting.selectorLabels" . | nindent 4 }}
  ports:
    - name: slurmdbd
      protocol: TCP
      port: {{ include "slurm.accounting.port" . }}
      targetPort: {{ include "slurm.accounting.port" . }}
{{- end }}{{- /* if .Values.accounting.enabled */}}
