{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if and .Values.accounting.enabled .Values.mariadb.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slurm.accounting.config.name" . }}
  namespace: {{ include "slurm.namespace" . }}
  labels:
    {{- include "slurm.accounting.labels" . | nindent 4 }}
data:
  slurmdbd.conf: |
    #
    ### GENERAL ###
    {{- range $idx := until (int .Values.controller.replicas | default 1) }}
    {{- if eq $idx 0 }}
    DbdHost={{- printf "%s-%d" (include "slurm.accounting.name" $) $idx }}
    {{- else }}{{- /* if eq $idx 0 */}}
    DbdBackupHost={{- printf "%s-%d" (include "slurm.accounting.name" $) $idx }}
    {{- end }}{{- /* if eq $idx 0 */}}
    {{- end }}{{- /* range $idx := until (int .Values.controller.replicas | default 1) */}}
    DbdPort={{- include "slurm.accounting.port" . }}
    PidFile=/var/run/slurmdbd.pid
    SlurmUser={{- include "slurm.user" . }}
    #
    ### AUTH ###
    AuthType=auth/slurm
    AuthAltTypes=auth/jwt
    AuthAltParameters=jwt_key={{- include "slurm.jwt.hs256.fullPath" . }}
    #
    ### STORAGE ###
    StorageType=accounting_storage/mysql
    StorageHost={{- include "mariadb.name" . }}
    StorageUser={{- .Values.mariadb.auth.username }}
    StoragePass=$MARIADB_PASSWORD
    StorageLoc={{- .Values.mariadb.auth.database }}
    StoragePort={{- default .Values.mariadb.primary.service.ports.mysql 3306 }}
    #
    ### LOGGING ###
    DebugLevel=info
    LogFile=/proc/1/fd/1
    LogTimeFormat=iso8601_ms
    #
    ### ARCHIEVE ###
    ArchiveDir=/tmp
    ArchiveEvents=YES
    ArchiveJobs=YES
    ArchiveResvs=YES
    ArchiveSteps=YES
    ArchiveSuspend=YES
    ArchiveTXN=YES
    ArchiveUsage=YES
    #
    ### PURGE ###
    PurgeEventAfter=12month
    PurgeJobAfter=12month
    PurgeResvAfter=2month
    PurgeStepAfter=2month
    PurgeSuspendAfter=1month
    PurgeTXNAfter=12month
    PurgeUsageAfter=12month
    #
    ### EXTRA CONFIG ###
    {{- with .Values.slurm.slurmdbdConfig -}}
    {{- . | nindent 4 -}}
    {{- end }}{{- /* with .Values.slurm.slurmdbdConfig */}}
{{- end }}
